# tasks file for ansikube
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add Docker apt-key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
    state: present

- name: Install docker and its dependencies
  apt: 
    name: "{{packages}}"
    state: present
    update_cache: true
  packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
    - docker-buildx-plugin 
    - docker-compose-plugin

- name: Start the docker engine
  service:
    name: docker
    state: started
    enabled: true
